version: '3'
services:
  app:
    build: .
    image: simple-dockerize-flask
    container_name: simple-dockerize-flask-app
    command: gunicorn -w 4 --reload -b 0.0.0.0:8080 main:app
    ports:
      - 8080:8080
    volumes:
      - .:/app
